# Generated by Django 3.2.7 on 2021-09-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0005_auto_20210927_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='data published'),
        ),
    ]
